language: java
jdk:
  - oraclejdk8
script: mvn verify
notifications:
  irc:
    channels:
      - "chat.freenode.net#fluo"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
